// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXB7l00lNyvQIIWbHJ4p2YkHowaAukP4Q',
    appId: '1:690847769075:web:a7c8dfd026e00a153b3286',
    messagingSenderId: '690847769075',
    projectId: 'rebu-fcea2',
    authDomain: 'rebu-fcea2.firebaseapp.com',
    storageBucket: 'rebu-fcea2.firebasestorage.app',
    measurementId: 'G-2S9GH2649N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwvbqN_-hGe-Go0Os4JeKorJygfez97g',
    appId: '1:690847769075:android:c31d1779b3e573a13b3286',
    messagingSenderId: '690847769075',
    projectId: 'rebu-fcea2',
    storageBucket: 'rebu-fcea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4qRfD3BJMTx9A-cwWw3-rUcqziWGVJo',
    appId: '1:690847769075:ios:5bdefe2a978e27fb3b3286',
    messagingSenderId: '690847769075',
    projectId: 'rebu-fcea2',
    storageBucket: 'rebu-fcea2.firebasestorage.app',
    iosBundleId: 'com.example.rebudriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP4qRfD3BJMTx9A-cwWw3-rUcqziWGVJo',
    appId: '1:690847769075:ios:5bdefe2a978e27fb3b3286',
    messagingSenderId: '690847769075',
    projectId: 'rebu-fcea2',
    storageBucket: 'rebu-fcea2.firebasestorage.app',
    iosBundleId: 'com.example.rebudriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXB7l00lNyvQIIWbHJ4p2YkHowaAukP4Q',
    appId: '1:690847769075:web:2e246d6dac511e3c3b3286',
    messagingSenderId: '690847769075',
    projectId: 'rebu-fcea2',
    authDomain: 'rebu-fcea2.firebaseapp.com',
    storageBucket: 'rebu-fcea2.firebasestorage.app',
    measurementId: 'G-98HGKBNPF3',
  );
}